export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const IS_SYNCING = 'IS_SYNCING';
export const DONE_SYNCING = 'DONE_SYNCING';
export const SYNC_ERROR = 'SYNC_ERROR';
export const SYNC_ERROR_RESOLVED = 'SYNC_ERROR_RESOLVED';

export const SET_PROJECT = 'SET_PROJECT';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_SAVED_PROJECT = 'UPDATE_SAVED_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const SHOW_WARNING = 'SHOW_WARNING';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';

export const COMMENT_ADDED = 'COMMENT_ADDED';
export const COMMENT_EDITED = 'COMMENT_EDITED';
export const COMMENT_DELETED = 'COMMENT_DELETED';
export const REFRESH_COMMENTS = 'REFRESH_COMMENTS';

export const ADD_CHANGE = 'ADD_CHANGE';
export const ADD_CHANGES = 'ADD_CHANGES';
export const LOAD_QUESTION_VERSIONS = 'LOAD_QUESTION_VERSIONS';
export const ERROR = 'ERROR';

export const SET_BASENAME = 'SET_BASENAME';
