export default [
  'Amphibians',
  'Animals taken from the wild',
  'Avian Eggs',
  'Birds',
  'Camelids',
  'Cats',
  'Cattle',
  'Cephalopods',
  'Deer',
  'Dogs',
  'Ferrets',
  'Fish - all other fish',
  'Fish - Zebra Fish',
  'Gerbils',
  'Goats',
  'Goats, sheep',
  'Guinea-pigs',
  'Hamsters',
  'Horses',
  'Mice',
  'N/A',
  'Non-human primates - new world (e.g. marmosets)',
  'Non-human primates - old world (e.g. macaques)',
  'Other species',
  'Pigs',
  'Rabbits',
  'Rats',
  'Reptiles',
  'Seals',
  'Sheep'
];
